version: '3.8'
services:
  app: 
    build: .
    container_name: app
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  db-data: